// ─────────────────────────────────────────────────────────────────
// NIRIKSHAN — Mock Data
// All synthetic data for frontend demonstration
// Replace with real API calls when backend is ready
// ─────────────────────────────────────────────────────────────────

// ── Projects ──────────────────────────────────────────────────────
export const mockProjects = [
  {
    id: 'PRJ-2024-0817',
    name: 'Community Hall Construction',
    constituency: 'Varanasi East',
    state: 'Uttar Pradesh',
    category: 'Community Infrastructure',
    amount: 1840000,
    spent: 1324800,
    completion: 72,
    status: 'ongoing',
    contractor: 'Shri Ram Constructions Pvt. Ltd.',
    agency: 'Varanasi Municipal Corporation',
    startDate: '2024-02-15',
    expectedEnd: '2026-08-31',
    location: { lat: 25.3176, lng: 82.9739 },
    riskScore: 34,
    riskLevel: 'low',
    photos: 4,
    behavioralMatch: 23,
  },
  {
    id: 'PRJ-2024-1203',
    name: 'Road Repair & Widening — NH-7 Link',
    constituency: 'Lucknow Central',
    state: 'Uttar Pradesh',
    category: 'Roads & Connectivity',
    amount: 4200000,
    spent: 4158000,
    completion: 99,
    status: 'review',
    contractor: 'Delta Infrastructure Ltd.',
    agency: 'PWD Lucknow',
    startDate: '2023-11-01',
    expectedEnd: '2024-06-30',
    location: { lat: 26.8467, lng: 80.9462 },
    riskScore: 87,
    riskLevel: 'critical',
    photos: 2,
    behavioralMatch: 87,
    flags: ['Impossible Timeline', 'Peer Deviation', 'Contractor Anomaly'],
  },
  {
    id: 'PRJ-2025-0034',
    name: 'Solar Street Lights — Ward 12',
    constituency: 'Patna Sahib',
    state: 'Bihar',
    category: 'Energy & Lighting',
    amount: 680000,
    spent: 680000,
    completion: 100,
    status: 'completed',
    contractor: 'GreenTech Solutions',
    agency: 'Patna Municipal Corp.',
    startDate: '2025-01-10',
    expectedEnd: '2025-04-30',
    location: { lat: 25.5941, lng: 85.1376 },
    riskScore: 12,
    riskLevel: 'low',
    photos: 8,
    behavioralMatch: 8,
  },
  {
    id: 'PRJ-2023-0891',
    name: 'Primary School Extension Block',
    constituency: 'Jaipur Rural',
    state: 'Rajasthan',
    category: 'Education',
    amount: 2800000,
    spent: 1120000,
    completion: 40,
    status: 'delayed',
    contractor: 'Rajputana Builders',
    agency: 'Rajasthan Edu. Dept.',
    startDate: '2023-06-01',
    expectedEnd: '2024-03-31',
    location: { lat: 26.9124, lng: 75.7873 },
    riskScore: 61,
    riskLevel: 'high',
    photos: 3,
    behavioralMatch: 55,
    flags: ['Delay > 180 days', 'Payment Anomaly'],
  },
  {
    id: 'PRJ-2024-0445',
    name: 'Drinking Water Pipeline — Phase 2',
    constituency: 'Nashik North',
    state: 'Maharashtra',
    category: 'Water Supply',
    amount: 6500000,
    spent: 5850000,
    completion: 90,
    status: 'ongoing',
    contractor: 'Aqua Systems Corp.',
    agency: 'MSEDCL Nashik',
    startDate: '2024-03-01',
    expectedEnd: '2026-09-30',
    location: { lat: 19.9975, lng: 73.7898 },
    riskScore: 42,
    riskLevel: 'medium',
    photos: 6,
    behavioralMatch: 38,
  },
  {
    id: 'PRJ-2022-1567',
    name: 'Panchayat Bhawan Renovation',
    constituency: 'Bhopal South',
    state: 'Madhya Pradesh',
    category: 'Government Buildings',
    amount: 950000,
    spent: 950000,
    completion: 100,
    status: 'completed',
    contractor: 'MP Infra Builders',
    agency: 'Bhopal Zila Panchayat',
    startDate: '2022-08-15',
    expectedEnd: '2023-02-28',
    location: { lat: 23.2599, lng: 77.4126 },
    riskScore: 19,
    riskLevel: 'low',
    photos: 5,
    behavioralMatch: 14,
  },
  {
    id: 'PRJ-2024-0782',
    name: 'Anganwadi Centre Construction — 5 Units',
    constituency: 'Raipur East',
    state: 'Chhattisgarh',
    category: 'Social Welfare',
    amount: 3100000,
    spent: 2945000,
    completion: 95,
    status: 'review',
    contractor: 'Delta Infrastructure Ltd.',
    agency: 'CG Women & Child Dev.',
    startDate: '2024-01-20',
    expectedEnd: '2024-12-31',
    location: { lat: 21.2514, lng: 81.6296 },
    riskScore: 79,
    riskLevel: 'high',
    photos: 1,
    behavioralMatch: 82,
    flags: ['Same Contractor as PRJ-2024-1203', 'Evidence Inconsistency', 'Network Anomaly'],
  },
  {
    id: 'PRJ-2025-0189',
    name: 'Sports Complex — Synthetic Track',
    constituency: 'Pune Cantonment',
    state: 'Maharashtra',
    category: 'Sports & Recreation',
    amount: 8200000,
    spent: 3280000,
    completion: 40,
    status: 'ongoing',
    contractor: 'SportsBuild India',
    agency: 'Pune Sports Authority',
    startDate: '2025-02-01',
    expectedEnd: '2026-12-31',
    location: { lat: 18.5204, lng: 73.8567 },
    riskScore: 28,
    riskLevel: 'low',
    photos: 7,
    behavioralMatch: 19,
  },
]

// ── Constituencies ─────────────────────────────────────────────────
export const mockConstituencies = [
  {
    id: 'CONST-UP-001',
    name: 'Varanasi East',
    state: 'Uttar Pradesh',
    mp: 'Rajendra Sharma',
    allocation: 25000000,
    spent: 19250000,
    projects: { total: 34, completed: 22, ongoing: 8, delayed: 2, review: 2 },
    completionRate: 78,
    peerRank: 'above',
    healthScore: 74,
  },
  {
    id: 'CONST-UP-002',
    name: 'Lucknow Central',
    state: 'Uttar Pradesh',
    mp: 'Priya Verma',
    allocation: 25000000,
    spent: 21500000,
    projects: { total: 41, completed: 18, ongoing: 14, delayed: 5, review: 4 },
    completionRate: 54,
    peerRank: 'below',
    healthScore: 48,
  },
  {
    id: 'CONST-BR-001',
    name: 'Patna Sahib',
    state: 'Bihar',
    mp: 'Anita Kumar',
    allocation: 25000000,
    spent: 22750000,
    projects: { total: 29, completed: 24, ongoing: 4, delayed: 1, review: 0 },
    completionRate: 88,
    peerRank: 'above',
    healthScore: 91,
  },
]

// ── National Stats ─────────────────────────────────────────────────
export const nationalStats = {
  projectsAnalysed: 14837,
  expenditureAnalysed: 847200000000, // ₹8,472 Cr
  patternsDiscovered: 247,
  anomaliesRequiringReview: 1893,
  activeInvestigations: 312,
  highRiskProjects: 428,
  statesMonitored: 28,
  constituenciesMonitored: 543,
}

// ── Behavioral DNA Data ─────────────────────────────────────────────
export const behavioralDNAData = {
  project: 'PRJ-2024-1203',
  dimensions: [
    { dimension: 'Financial',    score: 86, threshold: 65 },
    { dimension: 'Temporal',     score: 91, threshold: 65 },
    { dimension: 'Entity',       score: 74, threshold: 65 },
    { dimension: 'Documentation',score: 83, threshold: 65 },
    { dimension: 'Geographic',   score: 61, threshold: 65 },
    { dimension: 'Image',        score: 89, threshold: 65 },
  ],
  overallMatch: 87,
  similarPattern: '#47',
  riskScore: 87,
  breakdown: {
    paymentAnomalies: '+22',
    timelineImpossibility: '+19',
    contractorHistory: '+16',
    peerDeviation: '+15',
    networkAnomaly: '+11',
    documentationGap: '+4',
  },
}

// ── Peer Benchmarking ───────────────────────────────────────────────
export const peerBenchmarkData = {
  projectId: 'PRJ-2024-1203',
  metrics: {
    costPerUnit: {
      project: 4200,
      nationalPeer: 2100,
      localPeer: 2350,
      contractorAvg: 3800,
      nationalPercentile: 91,
      localPercentile: 97,
      contractorPercentile: 99,
    },
    completionSpeed: {
      project: 4,
      nationalPeer: 95,
      localPeer: 88,
      contractorAvg: 72,
      nationalPercentile: 99,
      localPercentile: 98,
      contractorPercentile: 97,
    },
    paymentCycle: {
      project: 2,
      nationalPeer: 18,
      localPeer: 21,
      contractorAvg: 15,
      nationalPercentile: 95,
      localPercentile: 94,
      contractorPercentile: 92,
    },
  },
  convergence: true,
  convergenceLevel: 'Multi-Benchmark',
}

// ── Network Graph ───────────────────────────────────────────────────
export const networkGraphData = {
  nodes: [
    { id: 'PRJ-1203', label: 'Road Project\nLucknow', type: 'project', risk: 87 },
    { id: 'PRJ-0782', label: 'Anganwadi\nRaipur', type: 'project', risk: 79 },
    { id: 'PRJ-0234', label: 'Bridge Repair\nKanpur', type: 'project', risk: 68 },
    { id: 'CONT-DI',  label: 'Delta\nInfrastructure', type: 'contractor', risk: 84 },
    { id: 'CONT-MP',  label: 'MP Infra\nBuilders', type: 'contractor', risk: 45 },
    { id: 'ENT-SJ',   label: 'Shell Entity\nJK Pvt.', type: 'entity', risk: 91 },
    { id: 'AGY-PWD',  label: 'PWD\nLucknow', type: 'agency', risk: 52 },
    { id: 'AGY-CG',   label: 'CG W&C\nDev. Dept', type: 'agency', risk: 48 },
  ],
  links: [
    { source: 'PRJ-1203', target: 'CONT-DI', type: 'normal' },
    { source: 'PRJ-0782', target: 'CONT-DI', type: 'suspicious' },
    { source: 'PRJ-0234', target: 'CONT-DI', type: 'suspicious' },
    { source: 'CONT-DI',  target: 'ENT-SJ',  type: 'suspicious' },
    { source: 'ENT-SJ',   target: 'AGY-PWD', type: 'suspicious' },
    { source: 'PRJ-1203', target: 'AGY-PWD', type: 'normal' },
    { source: 'PRJ-0782', target: 'AGY-CG',  type: 'normal' },
    { source: 'CONT-MP',  target: 'AGY-PWD', type: 'normal' },
  ],
}

// ── Evidence Verification ────────────────────────────────────────────
export const evidenceVerificationData = {
  projectId: 'PRJ-2024-1203',
  checks: [
    { id: 'gps',       label: 'GPS Coordinates',          status: 'pass',    detail: 'GPS data present and matches project location' },
    { id: 'timestamp', label: 'Photo Timestamp',          status: 'warning', detail: 'Timestamps show 3 photos taken within 4-minute window' },
    { id: 'similarity',label: 'Image Similarity',         status: 'fail',    detail: '94% perceptual similarity with photos from PRJ-0782 (Raipur)' },
    { id: 'exif',      label: 'EXIF Metadata',            status: 'warning', detail: 'EXIF data stripped from 2 of 4 photos' },
    { id: 'history',   label: 'Historical Match',         status: 'fail',    detail: 'Images match archive from 2022 Kanpur project' },
    { id: 'context',   label: 'Physical Context',         status: 'pass',    detail: 'Road infrastructure visible and consistent' },
    { id: 'solar',     label: 'Solar/Shadow Verification',status: 'warning', detail: 'Shadow angle inconsistent with claimed 14:30 capture time' },
    { id: 'docs',      label: 'Document Consistency',     status: 'fail',    detail: 'Measurement certificate totals don\'t match line items' },
  ],
  consistencyScore: 42,
  timelineFeasibility: {
    reportedDays: 4,
    expectedMin: 90,
    expectedMax: 140,
    feasibilityPercent: 18,
  },
}

// ── Forensic Reasoning ───────────────────────────────────────────────
export const forensicReasoningData = {
  projectId: 'PRJ-2024-1203',
  riskScore: 87,
  evidenceFor: [
    { id: 1, text: 'Same contractor executed 3 flagged projects simultaneously', weight: 22, source: 'Network Intelligence' },
    { id: 2, text: 'Reported construction timeline of 4 days is physically impossible', weight: 19, source: 'Timeline Engine' },
    { id: 3, text: 'Payment disbursed before inspection report filed', weight: 16, source: 'Payment Analysis' },
    { id: 4, text: '97th percentile cost deviation from local peer group', weight: 15, source: 'Peer Benchmarking' },
    { id: 5, text: 'Photo evidence reused from unrelated 2022 project', weight: 11, source: 'Evidence Verification' },
    { id: 6, text: 'Shell entity intermediary detected in payment chain', weight: 4, source: 'Network Intelligence' },
  ],
  evidenceAgainst: [
    { id: 1, text: 'Physical location GPS data correctly matches records', weight: 8, source: 'Evidence Verification' },
    { id: 2, text: 'Contractor holds valid registration and eligibility', weight: 5, source: 'Entity Database' },
    { id: 3, text: 'Road infrastructure visually present in photos', weight: 4, source: 'Image Analysis' },
  ],
  counterEvidenceApplied: false,
  counterEvidenceReasons: [
    'Region has limited qualified road contractors (12 registered vs national avg 34)',
    'Monsoon season may have compressed work window',
    'Emergency repair classification could explain accelerated timeline',
  ],
  adjustedRiskScore: 71,
  alternativeExplanations: [
    'Legitimate emergency repair under special dispensation',
    'Local contractor shortage forcing cross-district contractor use',
    'Phased work with partial completion at time of photograph',
  ],
  recommendedAction: 'Physical site verification with independent inspection team. Request original contractor work logs and labour records. Cross-verify payment chain beneficiary accounts.',
}

// ── Historical Case Replay ────────────────────────────────────────────
export const caseReplayData = {
  caseId: 'HIST-2019-MP-SAHARANPUR',
  title: 'MPLAD Fund Misuse — Saharanpur District',
  description: 'A documented case of irregularities in MPLAD fund utilization spanning 2017–2020, involving multiple contractors and implementing agencies.',
  years: [2017, 2018, 2019, 2020, 2021, 2022],
  warningYear: 2018,
  actualDiscoveryYear: 2021,
  timeline: {
    2017: {
      dataAvailable: true,
      projectsCreated: 12,
      anomaliesVisible: 2,
      nirikshan: {
        wouldFlag: false,
        riskScore: 34,
        indicators: ['Mild peer deviation'],
      },
      actual: 'Projects sanctioned. No investigation.',
    },
    2018: {
      dataAvailable: true,
      projectsCreated: 19,
      anomaliesVisible: 8,
      nirikshan: {
        wouldFlag: true,
        riskScore: 79,
        indicators: ['Impossible timeline detected', 'Contractor network anomaly', 'Payment sequence irregularity', 'Peer deviation: 91st percentile'],
        earlyWarning: true,
      },
      actual: 'Projects marked complete. Payments released. No investigation.',
    },
    2019: {
      dataAvailable: true,
      projectsCreated: 8,
      anomaliesVisible: 14,
      nirikshan: {
        wouldFlag: true,
        riskScore: 91,
        indicators: ['Pattern escalation detected', 'Evidence inconsistency: photos reused', 'Multi-benchmark convergence'],
      },
      actual: 'Additional projects sanctioned using same contractors.',
    },
    2020: {
      dataAvailable: true,
      projectsCreated: 3,
      anomaliesVisible: 17,
      nirikshan: {
        wouldFlag: true,
        riskScore: 94,
        indicators: ['Systemic pattern confirmed', 'Network fully mapped', 'CAG attention warranted'],
      },
      actual: 'Complaints filed by local activists. Under preliminary review.',
    },
    2021: {
      dataAvailable: true,
      projectsCreated: 0,
      anomaliesVisible: 17,
      nirikshan: { wouldFlag: true, riskScore: 96, indicators: ['Systemic fraud confirmed'] },
      actual: 'CAG investigation initiated. ₹3.2 Cr irregularity identified.',
    },
  },
  scoreBreakdown: [
    { factor: 'Peer Deviation',         contribution: 21, color: '#FF6B00' },
    { factor: 'Contractor Behaviour',   contribution: 18, color: '#FF3B5C' },
    { factor: 'Payment Anomaly',        contribution: 15, color: '#FFD60A' },
    { factor: 'Network Anomaly',        contribution: 13, color: '#9333EA' },
    { factor: 'Timeline Inconsistency', contribution: 11, color: '#3B82F6' },
    { factor: 'Documentation Signal',   contribution: 9,  color: '#6B7280' },
  ],
  totalScore: 87,
  timeSaved: '2.5 years',
  fundsAtRisk: 32000000,
}

// ── Live Intelligence Feed ─────────────────────────────────────────────
export const liveFeedAlerts = [
  { id: 1, type: 'critical',  icon: '🔴', text: 'New behavioral pattern detected — Rajasthan cluster (14 projects)', time: '2 min ago', action: 'Investigate' },
  { id: 2, type: 'warning',   icon: '🟠', text: 'Pattern mutation detected — Variant B of Pattern #47 emerging', time: '7 min ago', action: 'Review' },
  { id: 3, type: 'info',      icon: '📊', text: 'Peer anomaly: PRJ-2024-0891 at 97th percentile nationally', time: '12 min ago', action: 'Review' },
  { id: 4, type: 'critical',  icon: '📸', text: 'Evidence inconsistency detected — PRJ-2024-1203 photo reuse', time: '18 min ago', action: 'Verify' },
  { id: 5, type: 'warning',   icon: '🕸️', text: 'Suspicious relationship detected — Delta Infrastructure linked to 3 flagged projects', time: '34 min ago', action: 'Map' },
  { id: 6, type: 'info',      icon: '⏱️', text: 'Timeline impossibility: 4-day construction reported for 90-day project', time: '41 min ago', action: 'Review' },
  { id: 7, type: 'success',   icon: '✅', text: 'Investigation closed — PRJ-2023-0234: No irregularity found', time: '1 hr ago', action: 'Archive' },
  { id: 8, type: 'critical',  icon: '🚨', text: 'Multi-benchmark convergence: PRJ-2024-0782 flagged at national + local + contractor level', time: '2 hr ago', action: 'Escalate' },
]

// ── State Risk Data (for India map) ────────────────────────────────────
export const stateRiskData: Record<string, { risk: number; projects: number; flagged: number; amount: string }> = {
  'Uttar Pradesh':      { risk: 72, projects: 1847, flagged: 234, amount: '₹847 Cr' },
  'Bihar':              { risk: 68, projects: 923,  flagged: 145, amount: '₹423 Cr' },
  'Rajasthan':          { risk: 61, projects: 1124, flagged: 118, amount: '₹512 Cr' },
  'Madhya Pradesh':     { risk: 58, projects: 987,  flagged: 97,  amount: '₹389 Cr' },
  'Maharashtra':        { risk: 41, projects: 1456, flagged: 87,  amount: '₹621 Cr' },
  'Karnataka':          { risk: 38, projects: 834,  flagged: 54,  amount: '₹412 Cr' },
  'Tamil Nadu':         { risk: 32, projects: 945,  flagged: 41,  amount: '₹478 Cr' },
  'Gujarat':            { risk: 29, projects: 876,  flagged: 38,  amount: '₹394 Cr' },
  'West Bengal':        { risk: 54, projects: 1123, flagged: 89,  amount: '₹534 Cr' },
  'Andhra Pradesh':     { risk: 44, projects: 678,  flagged: 62,  amount: '₹345 Cr' },
  'Telangana':          { risk: 36, projects: 523,  flagged: 34,  amount: '₹287 Cr' },
  'Odisha':             { risk: 49, projects: 456,  flagged: 56,  amount: '₹223 Cr' },
  'Kerala':             { risk: 21, projects: 534,  flagged: 19,  amount: '₹298 Cr' },
  'Jharkhand':          { risk: 63, projects: 389,  flagged: 71,  amount: '₹189 Cr' },
  'Assam':              { risk: 55, projects: 412,  flagged: 62,  amount: '₹201 Cr' },
  'Punjab':             { risk: 33, projects: 534,  flagged: 28,  amount: '₹312 Cr' },
  'Haryana':            { risk: 35, projects: 467,  flagged: 31,  amount: '₹287 Cr' },
  'Chhattisgarh':       { risk: 57, projects: 378,  flagged: 59,  amount: '₹189 Cr' },
  'Uttarakhand':        { risk: 42, projects: 289,  flagged: 34,  amount: '₹167 Cr' },
  'Himachal Pradesh':   { risk: 28, projects: 234,  flagged: 18,  amount: '₹134 Cr' },
  'Goa':                { risk: 18, projects: 67,   flagged: 4,   amount: '₹45 Cr'  },
  'Tripura':            { risk: 47, projects: 123,  flagged: 21,  amount: '₹67 Cr'  },
  'Meghalaya':          { risk: 39, projects: 98,   flagged: 14,  amount: '₹54 Cr'  },
  'Manipur':            { risk: 51, projects: 112,  flagged: 19,  amount: '₹61 Cr'  },
  'Nagaland':           { risk: 44, projects: 89,   flagged: 12,  amount: '₹48 Cr'  },
  'Arunachal Pradesh':  { risk: 46, projects: 134,  flagged: 17,  amount: '₹73 Cr'  },
  'Mizoram':            { risk: 31, projects: 78,   flagged: 8,   amount: '₹42 Cr'  },
  'Sikkim':             { risk: 22, projects: 45,   flagged: 3,   amount: '₹28 Cr'  },
}
